# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LTN_Gibbs_C <- function(results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, gam_shape_p, gam_rate_p, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_C`, results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, gam_shape_p, gam_rate_p, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin)
}

LTN_Gibbs_Perp_C <- function(results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, chain_phi_dki, psi_chain_k_ipd, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_Perp_C`, results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, chain_phi_dki, psi_chain_k_ipd, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin)
}

