# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LTN_Gibbs_C <- function(results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, gam_shape_p, gam_rate_p, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_C`, results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, gam_shape_p, gam_rate_p, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin)
}

LTN_Gibbs_cov_C <- function(results, f_pg, f_iwish, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, U_nodes, a_U, b_U, Phi_U, L_nodes, a_L, b_L, Phi_L, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, p_U, p_L, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_cov_C`, results, f_pg, f_iwish, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, U_nodes, a_U, b_U, Phi_U, L_nodes, a_L, b_L, Phi_L, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, p_U, p_L, D, V, alpha, iterations, warmup, thin)
}

LTN_Gibbs_cov_block_C <- function(results, f_pg, f_iwish, f_bglasso, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, U_nodes, a_U, b_U, Phi_U, L_nodes, a_L, b_L, Phi_L, r, q, noise, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, p_U, p_L, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_cov_block_C`, results, f_pg, f_iwish, f_bglasso, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, U_nodes, a_U, b_U, Phi_U, L_nodes, a_L, b_L, Phi_L, r, q, noise, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, p_U, p_L, D, V, alpha, iterations, warmup, thin)
}

LTN_Gibbs_Perp_C <- function(results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, chain_phi_dki, psi_chain_k_ipd, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_Perp_C`, results, f_pg, Sigma_ppk, W_ppk, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, chain_phi_dki, psi_chain_k_ipd, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, D, V, alpha, iterations, warmup, thin)
}

LTN_Gibbs_cov_gwish_C <- function(results, f_pg, f_iwish, f_gwish, Sigma_ppk, W_ppk, G_L_ppk, g_prior, upper_coord_L, exist_ind_L_tk, rates_L_tk, waiting_times_L_k, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, U_nodes, a_U, b_U, Phi_U, L_nodes, a_L, b_L, Phi_L, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, chain_existind_L_itk, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, p_U, p_L, num_upptri_L, D, V, alpha, iterations, warmup, thin) {
    .Call(`_LTNLDA_LTN_Gibbs_cov_gwish_C`, results, f_pg, f_iwish, f_gwish, Sigma_ppk, W_ppk, G_L_ppk, g_prior, upper_coord_L, exist_ind_L_tk, rates_L_tk, waiting_times_L_k, mu_pk, v_pdk, psi_pdk, kappa_pdk, theta_kda, beta_kdv, Lambda_inv, U_nodes, a_U, b_U, Phi_U, L_nodes, a_L, b_L, Phi_L, chain_phi_dki, psi_chain_k_ipd, mu_chain_k_ip, Sigma_chain_k_ipp, chain_existind_L_itk, nc_dnt, dt, descendants_mat, ta, docs, ancestors, internal_nodes, leaf_success, leaf_failures, K, p, p_U, p_L, num_upptri_L, D, V, alpha, iterations, warmup, thin)
}

